More fixes.

diff --git a/.github/workflows/full_linux.yml b/.github/workflows/full_linux.yml
--- a/.github/workflows/full_linux.yml
+++ b/.github/workflows/full_linux.yml
@@ -23,8 +23,8 @@ jobs:
 
     - name: Update
       run: |
-        sudo add-apt-repository universe
-        sudo apt-get update
+        sudo add-apt-repository universe -y
+        sudo apt-get update || { echo "apt-get update failed"; exit 1; }
       
     - name: Install OpenGL dev
       run: sudo apt-get install -y xorg-dev libglu1-mesa-dev mesa-common-dev
@@ -55,14 +55,19 @@ jobs:
       
     - name: Install python dependencies
       run: sudo apt-get install -y libssl-dev libffi-dev python3
+      
     - name: Verify libshaderc-dev availability
       run: |
         apt-cache policy libshaderc-dev
     
+    - name: Install libshaderc-dev
+      run: |
+        sudo apt-get install -y libshaderc-dev || { echo "Install failed"; exit 1; }
+        
     - name: Install vulkan
       if: github.ref_name == 'vulkan'
       run: |
-        sudo apt-get install -y libvulkan1 libvulkan-dev mesa-vulkan-drivers vulkan-validationlayers libshaderc-dev
+        sudo apt-get install -y libvulkan1 libvulkan-dev mesa-vulkan-drivers vulkan-validationlayers
 
     - name: Synchronize clock
       run: |
